refactor(experimental): add bigint support to `fast-stable-stringify`
solana-foundation/solana-web3.js pull request #2014
Opened 2024-01-09 01:27 UTC by buffalojoec

This PR adds custom `bigint` support to the cache key functions used by the
resolvers within `DataLoader`.

The library used to create these cache keys - `fast-stable-stringify` - does not
support `bigint`, so I've added a custom `cacheKey` function to convert `bigint`
to `string` in all parameter objects before handing the object over to
`fast-stable-stringify`.

This somewhat defeats the "fast" purpose of `fast-stable-stringify`, but as
mentioned in the function's comments, considering the size of these parameter
objects, the effect should be negligible.

Closes #1986

2024-01-09 01:28 UTC, buffalojoec commented
Current dependencies on/for this PR:
* `master`
  * **PR #2014** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2014?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2014?utm_source=stack-comment).

2024-01-09 06:43 UTC, steveluscher requested changes
Oooh, hang on though. I wonder if this is our chance to fork `fast-stable-stringify` and just add a `case` to the `switch (typeof val)` in there, handle bigints, and get out. Thoughts?

2024-01-09 06:44 UTC, buffalojoec commented
> Oooh, hang on though. I wonder if this is our chance to fork `fast-stable-stringify` and just add a `case` to the `switch (typeof val)` in there, handle bigints, and get out. Thoughts?

I was close to doing that, tbh. Do we want to just put it in the Web3.js monorepo?

2024-01-09 06:52 UTC, buffalojoec commented
In addition to the fact it hasn't had a new version in 6 years, the repository is mostly perf testing. We could probably slim it down quite a bit and add it as a package in Web3.js. Seems like it would need minimal support.

2024-01-09 07:04 UTC, steveluscher commented
![do-it.gif](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lE1zD7Jpg6mWNv3djNKZ/4fae2bc7-150d-438b-bd6b-fe85166a110e.gif)

I wonder how fast an object hash would be in JS if you just walked an object depth first, turned everything you find into a byte buffer, and the called `crypto.subtle.digest()` on the whole thing.

```ts
function hashObject(obj) {
  const data = new Uint8Array((function*() {
    // Walk the object in the usual ways...
    Object.keys(obj).forEach(key => {
      const value = obj[key];
      switch (typeof value) {
        case 'string':
          yield* stringToBytes(value);
          break;
        case 'number': {
          const floatArray = new Float64Array(1);
          floatArray[0] = value;
          yield* new Uint8Array(floatArray.buffer);
        /* etc etc etc */
      }
    });
  })());
  const hash = await crypto.subtle.digest('SHA-256', data);
  return bytesToHex(hash);
}
```

2024-01-09 07:04 UTC, steveluscher commented
It would be async though.

2024-01-09 07:13 UTC, steveluscher commented
Somewhat related (not really though).

https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-521460510

2024-01-09 08:15 UTC, lorisleiva commented
How about using the battle tested original [`json-stable-stringify` package](https://www.npmjs.com/package/json-stable-stringify) from which the "fast" one forked from.

It is downloaded over 3 million times a week and was last published 2 months ago as opposed to all the "fast" versions that were published 6 years ago. I'm pretty sure the main package would have had some extra optimisations by now.

2024-01-09 08:23 UTC, buffalojoec commented
> How about using the battle tested original [`json-stable-stringify` package](https://www.npmjs.com/package/json-stable-stringify) from which the "fast" one forked from?
> 
> It is downloaded over 3 million times a week and was last published 2 months ago as opposed to all the "fast" versions that were published 6 years ago. I'm pretty sure the main package would have had some extra optimisations by now.

This one looks like it might work. I can see support for setting the global `BigInt.toJson` or defining a `replacer`.

2024-01-09 20:50 UTC, closed without merging

2024-01-10 00:07 UTC, steveluscher commented
> I can see support for setting the global `BigInt.toJson`…

Definitely definitely don't modify prototypes. web3.js will break in the first app that protects against monkeypatched builtins.

> …or defining a `replacer`.

A replacer doesn't do what we want. What we want is this:

```ts
stringify({foo: 1n}); // {"foo":1n}
```

The _most_ a replacer will let us do ([demo](https://stackblitz.com/edit/typescript-ue5rcm?devToolsHeight=33&file=index.ts)) is this:

```ts
stringify({foo: 1n}); // {"foo":"1n"}
```

…which is a hash collision with this:

```ts
stringify({foo: '1n'}); // {"foo":"1n"} 
```

The whole root of the problem here is that we dgaf about JSON – we just need a hash – but all these libraries have as a goal the production of valid JSON.

2024-01-10 00:10 UTC, steveluscher commented
Also, it's fucking huge. https://bundlephobia.com/package/json-stable-stringify@1.1.0 
<img width="2153" alt="image" src="https://github.com/solana-labs/solana-web3.js/assets/13243/1cbc2895-0042-4a4c-8a13-04e6f27bcc34">