Make __DEV__ robust to environments without process.env
solana-foundation/solana-web3.js pull request #2714
Opened 2024-05-14 10:48 UTC by mcintyre94

This PR updates the logic used to define `__DEV__` in the build scripts env-shim, so that if `process.env` doesn't exist  in the environment where we end up running doesn't exist, then it returns true instead of throwing a runtime error

The generated code in eg `packages/errors/dist/index.browser.cjs` is now:

```
// ../build-scripts/env-shim.ts
function isDevelopment() {
  if (typeof process === "object" && process.env) {
    return process["env"].NODE_ENV === "development";
  }
  return true;
}
var __DEV__ = /* @__PURE__ */ isDevelopment();
```

Where previously it was:
```
// ../build-scripts/env-shim.ts
var __DEV__ = /* @__PURE__ */ (() => process["env"].NODE_ENV === "development")();
```

2024-05-14 12:18 UTC, lorisleiva commented
Let me know if this is The Right Way as I'll need to update the generate program repos (and the generator).

2024-05-14 17:37 UTC, steveluscher commented
So confused why React can get away with just this. 

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lE1zD7Jpg6mWNv3djNKZ/7d8bcf72-3f34-4ea0-bc11-9854c85a511f.png)

2024-05-14 17:57 UTC, steveluscher requested changes
Zooming out a bit:

1. This ‘call a function to get the value of this’ is dumb, and the only reason that I wrote it this way is because of how `inject` works in esbuild. Literally all I wanted to do was to [inject](https://esbuild.github.io/api/#inject), at the top level scope, the statement `const __DEV__ = process.env.NODE_ENV === 'development';`
2. See this conversation: https://github.com/evanw/esbuild/issues/2695
3. Have you tested that this actually results in code being reaped by a downstream bundler when `process.env.NODE_ENV` is `"production"`. I sort of suspect because of the added dynamic check of a global (`typeof process`) that this will never result in dead-code elimination.

2024-05-15 17:24 UTC, mcintyre94 commented
I'm going to close this for now, I was able to use a Vite plugin to replace in the generated JS code. If this is something others end up needing then we can consider publishing a plugin to use without messing with the build output for everyone else.

2024-05-15 17:24 UTC, closed without merging